# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biiling_project_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1395, 1029)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BotFrame = QtWidgets.QFrame(self.centralwidget)
        self.BotFrame.setGeometry(QtCore.QRect(20, 414, 1351, 581))
        self.BotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BotFrame.setObjectName("BotFrame")
        self.InfoFrame = QtWidgets.QFrame(self.BotFrame)
        self.InfoFrame.setGeometry(QtCore.QRect(0, 0, 1351, 81))
        self.InfoFrame.setStyleSheet("")
        self.InfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InfoFrame.setObjectName("InfoFrame")
        self.label_7 = QtWidgets.QLabel(self.InfoFrame)
        self.label_7.setGeometry(QtCore.QRect(385, 46, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.CNRInput = QtWidgets.QLineEdit(self.InfoFrame)
        self.CNRInput.setGeometry(QtCore.QRect(190, 44, 161, 31))
        self.CNRInput.setText("")
        self.CNRInput.setReadOnly(True)
        self.CNRInput.setObjectName("CNRInput")
        self.CLRNumber = QtWidgets.QLineEdit(self.InfoFrame)
        self.CLRNumber.setGeometry(QtCore.QRect(1191, 46, 151, 31))
        self.CLRNumber.setText("")
        self.CLRNumber.setReadOnly(True)
        self.CLRNumber.setObjectName("CLRNumber")
        self.CNEInput = QtWidgets.QLineEdit(self.InfoFrame)
        self.CNEInput.setGeometry(QtCore.QRect(521, 48, 161, 31))
        self.CNEInput.setText("")
        self.CNEInput.setReadOnly(True)
        self.CNEInput.setObjectName("CNEInput")
        self.FrStationInput = QtWidgets.QLineEdit(self.InfoFrame)
        self.FrStationInput.setGeometry(QtCore.QRect(190, 4, 161, 31))
        self.FrStationInput.setText("")
        self.FrStationInput.setReadOnly(True)
        self.FrStationInput.setObjectName("FrStationInput")
        self.label_9 = QtWidgets.QLabel(self.InfoFrame)
        self.label_9.setGeometry(QtCore.QRect(1060, 44, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.InfoFrame)
        self.label_5.setGeometry(QtCore.QRect(10, 44, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.InfoFrame)
        self.label_4.setGeometry(QtCore.QRect(10, 4, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.InfoFrame)
        self.label_6.setGeometry(QtCore.QRect(383, 4, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.InfoFrame)
        self.label_8.setGeometry(QtCore.QRect(1060, 5, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ToStationInput = QtWidgets.QLineEdit(self.InfoFrame)
        self.ToStationInput.setGeometry(QtCore.QRect(521, 6, 161, 31))
        self.ToStationInput.setText("")
        self.ToStationInput.setReadOnly(True)
        self.ToStationInput.setObjectName("ToStationInput")
        self.DateInput = QtWidgets.QDateTimeEdit(self.InfoFrame)
        self.DateInput.setGeometry(QtCore.QRect(1190, 6, 151, 31))
        self.DateInput.setObjectName("DateInput")
        self.VechicleNumInput = QtWidgets.QLineEdit(self.InfoFrame)
        self.VechicleNumInput.setGeometry(QtCore.QRect(875, 7, 171, 31))
        self.VechicleNumInput.setObjectName("VechicleNumInput")
        self.label_21 = QtWidgets.QLabel(self.InfoFrame)
        self.label_21.setGeometry(QtCore.QRect(700, 5, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.ItemNameInput = QtWidgets.QLineEdit(self.BotFrame)
        self.ItemNameInput.setGeometry(QtCore.QRect(160, 93, 321, 31))
        self.ItemNameInput.setText("")
        self.ItemNameInput.setReadOnly(False)
        self.ItemNameInput.setObjectName("ItemNameInput")
        self.label_10 = QtWidgets.QLabel(self.BotFrame)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.BotFrame)
        self.label_11.setGeometry(QtCore.QRect(500, 92, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.QtyInput = QtWidgets.QLineEdit(self.BotFrame)
        self.QtyInput.setGeometry(QtCore.QRect(580, 92, 161, 31))
        self.QtyInput.setObjectName("QtyInput")
        self.label_20 = QtWidgets.QLabel(self.BotFrame)
        self.label_20.setGeometry(QtCore.QRect(1083, 501, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.AddItemButton = QtWidgets.QPushButton(self.BotFrame)
        self.AddItemButton.setGeometry(QtCore.QRect(1218, 95, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddItemButton.setFont(font)
        self.AddItemButton.setObjectName("AddItemButton")
        self.TotalAmountLabel = QtWidgets.QLabel(self.BotFrame)
        self.TotalAmountLabel.setGeometry(QtCore.QRect(1220, 500, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TotalAmountLabel.setFont(font)
        self.TotalAmountLabel.setObjectName("TotalAmountLabel")
        self.TableAreaBottom = QtWidgets.QTableView(self.BotFrame)
        self.TableAreaBottom.setGeometry(QtCore.QRect(0, 130, 1351, 231))
        self.TableAreaBottom.setObjectName("TableAreaBottom")
        self.NewLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.NewLrButton.setGeometry(QtCore.QRect(10, 491, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NewLrButton.setFont(font)
        self.NewLrButton.setObjectName("NewLrButton")
        self.EditLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.EditLrButton.setGeometry(QtCore.QRect(180, 491, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EditLrButton.setFont(font)
        self.EditLrButton.setObjectName("EditLrButton")
        self.CancelLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.CancelLrButton.setGeometry(QtCore.QRect(330, 491, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CancelLrButton.setFont(font)
        self.CancelLrButton.setObjectName("CancelLrButton")
        self.PrintLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.PrintLrButton.setGeometry(QtCore.QRect(500, 491, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PrintLrButton.setFont(font)
        self.PrintLrButton.setObjectName("PrintLrButton")
        self.RateInput = QtWidgets.QLineEdit(self.BotFrame)
        self.RateInput.setGeometry(QtCore.QRect(840, 92, 211, 31))
        self.RateInput.setObjectName("RateInput")
        self.label_22 = QtWidgets.QLabel(self.BotFrame)
        self.label_22.setGeometry(QtCore.QRect(760, 91, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.HChargeInput = QtWidgets.QLineEdit(self.BotFrame)
        self.HChargeInput.setGeometry(QtCore.QRect(1090, 381, 211, 31))
        self.HChargeInput.setObjectName("HChargeInput")
        self.labbb = QtWidgets.QLabel(self.BotFrame)
        self.labbb.setGeometry(QtCore.QRect(970, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labbb.setFont(font)
        self.labbb.setObjectName("labbb")
        self.CrossingInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CrossingInput.setGeometry(QtCore.QRect(1090, 421, 211, 31))
        self.CrossingInput.setObjectName("CrossingInput")
        self.llab1 = QtWidgets.QLabel(self.BotFrame)
        self.llab1.setGeometry(QtCore.QRect(970, 420, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.llab1.setFont(font)
        self.llab1.setObjectName("llab1")
        self.label_25 = QtWidgets.QLabel(self.BotFrame)
        self.label_25.setGeometry(QtCore.QRect(10, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.CNRGSTInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNRGSTInput.setGeometry(QtCore.QRect(130, 381, 211, 31))
        self.CNRGSTInput.setObjectName("CNRGSTInput")
        self.CNEGSTInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNEGSTInput.setGeometry(QtCore.QRect(130, 421, 211, 31))
        self.CNEGSTInput.setObjectName("CNEGSTInput")
        self.label_26 = QtWidgets.QLabel(self.BotFrame)
        self.label_26.setGeometry(QtCore.QRect(10, 420, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.BotFrame)
        self.label_27.setGeometry(QtCore.QRect(380, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.LRTypeInput = QtWidgets.QComboBox(self.BotFrame)
        self.LRTypeInput.setGeometry(QtCore.QRect(580, 380, 101, 31))
        self.LRTypeInput.setObjectName("LRTypeInput")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.setItemText(2, "")
        self.TopFrame = QtWidgets.QFrame(self.centralwidget)
        self.TopFrame.setGeometry(QtCore.QRect(21, -7, 1351, 421))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TopFrame.setFont(font)
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.TableAreaTop = QtWidgets.QTableView(self.TopFrame)
        self.TableAreaTop.setGeometry(QtCore.QRect(0, 51, 1351, 371))
        self.TableAreaTop.setObjectName("TableAreaTop")
        self.label = QtWidgets.QLabel(self.TopFrame)
        self.label.setGeometry(QtCore.QRect(10, 12, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CLRSearchInput = QtWidgets.QLineEdit(self.TopFrame)
        self.CLRSearchInput.setGeometry(QtCore.QRect(180, 12, 241, 31))
        self.CLRSearchInput.setText("")
        self.CLRSearchInput.setObjectName("CLRSearchInput")
        self.SearchLRButton = QtWidgets.QPushButton(self.TopFrame)
        self.SearchLRButton.setGeometry(QtCore.QRect(432, 12, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SearchLRButton.setFont(font)
        self.SearchLRButton.setObjectName("SearchLRButton")
        self.label_2 = QtWidgets.QLabel(self.TopFrame)
        self.label_2.setGeometry(QtCore.QRect(600, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.DateLabel = QtWidgets.QLabel(self.TopFrame)
        self.DateLabel.setGeometry(QtCore.QRect(700, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DateLabel.setFont(font)
        self.DateLabel.setObjectName("DateLabel")
        self.label_3 = QtWidgets.QLabel(self.TopFrame)
        self.label_3.setGeometry(QtCore.QRect(970, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.BranchComboBox = QtWidgets.QComboBox(self.TopFrame)
        self.BranchComboBox.setGeometry(QtCore.QRect(1170, 10, 101, 31))
        self.BranchComboBox.setObjectName("BranchComboBox")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1395, 26))
        self.menubar.setObjectName("menubar")
        self.menuLR_Booking = QtWidgets.QMenu(self.menubar)
        self.menuLR_Booking.setObjectName("menuLR_Booking")
        self.menuHep = QtWidgets.QMenu(self.menubar)
        self.menuHep.setObjectName("menuHep")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuInvoice = QtWidgets.QMenu(self.menubar)
        self.menuInvoice.setObjectName("menuInvoice")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPrevious_Records = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Records.setObjectName("actionPrevious_Records")
        self.actionFile_search = QtWidgets.QAction(MainWindow)
        self.actionFile_search.setObjectName("actionFile_search")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuHep.addAction(self.actionPrevious_Records)
        self.menuHep.addAction(self.actionFile_search)
        self.menuHep.addAction(self.actionExport)
        self.menufile.addAction(self.actionExit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuLR_Booking.menuAction())
        self.menubar.addAction(self.menuHep.menuAction())
        self.menubar.addAction(self.menuInvoice.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Billing Application"))
        self.label_7.setText(_translate("MainWindow", "CNE:"))
        self.label_9.setText(_translate("MainWindow", "CLR :"))
        self.label_5.setText(_translate("MainWindow", "CNR:"))
        self.label_4.setText(_translate("MainWindow", "From Station:"))
        self.label_6.setText(_translate("MainWindow", "To Station :"))
        self.label_8.setText(_translate("MainWindow", "Date :"))
        self.label_21.setText(_translate("MainWindow", "VECHICLE NO:"))
        self.label_10.setText(_translate("MainWindow", "ITEM Name:"))
        self.label_11.setText(_translate("MainWindow", "QTY:"))
        self.label_20.setText(_translate("MainWindow", "RS .P"))
        self.AddItemButton.setText(_translate("MainWindow", "Add Item"))
        self.TotalAmountLabel.setText(_translate("MainWindow", "1000"))
        self.NewLrButton.setText(_translate("MainWindow", "NEW LR"))
        self.EditLrButton.setText(_translate("MainWindow", "EDIT LR"))
        self.CancelLrButton.setText(_translate("MainWindow", "CANCEL LR"))
        self.PrintLrButton.setText(_translate("MainWindow", "PRINT LR"))
        self.label_22.setText(_translate("MainWindow", "RATE:"))
        self.labbb.setText(_translate("MainWindow", "H Charge:"))
        self.llab1.setText(_translate("MainWindow", "Crossing:"))
        self.label_25.setText(_translate("MainWindow", "CNR GST:"))
        self.label_26.setText(_translate("MainWindow", "CNE GST:"))
        self.label_27.setText(_translate("MainWindow", "LR TYPE:"))
        self.LRTypeInput.setItemText(0, _translate("MainWindow", "TO PAY"))
        self.LRTypeInput.setItemText(1, _translate("MainWindow", "PAID"))
        self.label.setText(_translate("MainWindow", "CLR Number:"))
        self.SearchLRButton.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Date:"))
        self.DateLabel.setText(_translate("MainWindow", "0/0/0000"))
        self.label_3.setText(_translate("MainWindow", "Branch Code:"))
        self.BranchComboBox.setItemText(0, _translate("MainWindow", "A"))
        self.BranchComboBox.setItemText(1, _translate("MainWindow", "B"))
        self.BranchComboBox.setItemText(2, _translate("MainWindow", "C"))
        self.BranchComboBox.setItemText(3, _translate("MainWindow", "D"))
        self.menuLR_Booking.setTitle(_translate("MainWindow", "LR Booking"))
        self.menuHep.setTitle(_translate("MainWindow", "Search"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuInvoice.setTitle(_translate("MainWindow", "Invoice "))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionPrevious_Records.setText(_translate("MainWindow", "Invoice search"))
        self.actionFile_search.setText(_translate("MainWindow", "File search"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
