# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biiling_project_UI2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1881, 1029)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTabWidget.setGeometry(QtCore.QRect(10, 0, 1881, 981))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.MainTabWidget.setFont(font)
        self.MainTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.MainTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainTabWidget.setTabsClosable(False)
        self.MainTabWidget.setTabBarAutoHide(False)
        self.MainTabWidget.setObjectName("MainTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.BotFrame = QtWidgets.QFrame(self.tab)
        self.BotFrame.setGeometry(QtCore.QRect(-1, 412, 1351, 581))
        self.BotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BotFrame.setObjectName("BotFrame")
        self.ItemNameInput = QtWidgets.QLineEdit(self.BotFrame)
        self.ItemNameInput.setGeometry(QtCore.QRect(160, 93, 321, 31))
        self.ItemNameInput.setText("")
        self.ItemNameInput.setReadOnly(False)
        self.ItemNameInput.setObjectName("ItemNameInput")
        self.label_10 = QtWidgets.QLabel(self.BotFrame)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.BotFrame)
        self.label_11.setGeometry(QtCore.QRect(500, 92, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.QtyInput = QtWidgets.QLineEdit(self.BotFrame)
        self.QtyInput.setGeometry(QtCore.QRect(580, 92, 161, 31))
        self.QtyInput.setObjectName("QtyInput")
        self.label_20 = QtWidgets.QLabel(self.BotFrame)
        self.label_20.setGeometry(QtCore.QRect(1093, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.AddItemButton = QtWidgets.QPushButton(self.BotFrame)
        self.AddItemButton.setGeometry(QtCore.QRect(1218, 95, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.AddItemButton.setFont(font)
        self.AddItemButton.setObjectName("AddItemButton")
        self.TotalAmountLabel = QtWidgets.QLabel(self.BotFrame)
        self.TotalAmountLabel.setGeometry(QtCore.QRect(1230, 479, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.TotalAmountLabel.setFont(font)
        self.TotalAmountLabel.setObjectName("TotalAmountLabel")
        self.TableAreaBottom = QtWidgets.QTableView(self.BotFrame)
        self.TableAreaBottom.setGeometry(QtCore.QRect(0, 130, 1351, 231))
        self.TableAreaBottom.setObjectName("TableAreaBottom")
        self.NewLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.NewLrButton.setGeometry(QtCore.QRect(20, 470, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.NewLrButton.setFont(font)
        self.NewLrButton.setObjectName("NewLrButton")
        self.EditLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.EditLrButton.setGeometry(QtCore.QRect(190, 470, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.EditLrButton.setFont(font)
        self.EditLrButton.setObjectName("EditLrButton")
        self.CancelLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.CancelLrButton.setGeometry(QtCore.QRect(340, 470, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CancelLrButton.setFont(font)
        self.CancelLrButton.setObjectName("CancelLrButton")
        self.PrintLrButton = QtWidgets.QPushButton(self.BotFrame)
        self.PrintLrButton.setGeometry(QtCore.QRect(510, 470, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.PrintLrButton.setFont(font)
        self.PrintLrButton.setObjectName("PrintLrButton")
        self.RateInput = QtWidgets.QLineEdit(self.BotFrame)
        self.RateInput.setGeometry(QtCore.QRect(840, 92, 211, 31))
        self.RateInput.setObjectName("RateInput")
        self.label_22 = QtWidgets.QLabel(self.BotFrame)
        self.label_22.setGeometry(QtCore.QRect(760, 91, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.HChargeInput = QtWidgets.QLineEdit(self.BotFrame)
        self.HChargeInput.setGeometry(QtCore.QRect(1090, 381, 211, 31))
        self.HChargeInput.setObjectName("HChargeInput")
        self.labbb = QtWidgets.QLabel(self.BotFrame)
        self.labbb.setGeometry(QtCore.QRect(970, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.labbb.setFont(font)
        self.labbb.setObjectName("labbb")
        self.CrossingInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CrossingInput.setGeometry(QtCore.QRect(1090, 421, 211, 31))
        self.CrossingInput.setObjectName("CrossingInput")
        self.llab1 = QtWidgets.QLabel(self.BotFrame)
        self.llab1.setGeometry(QtCore.QRect(970, 420, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.llab1.setFont(font)
        self.llab1.setObjectName("llab1")
        self.label_25 = QtWidgets.QLabel(self.BotFrame)
        self.label_25.setGeometry(QtCore.QRect(10, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.CNRGSTInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNRGSTInput.setGeometry(QtCore.QRect(130, 381, 211, 31))
        self.CNRGSTInput.setObjectName("CNRGSTInput")
        self.CNEGSTInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNEGSTInput.setGeometry(QtCore.QRect(130, 421, 211, 31))
        self.CNEGSTInput.setObjectName("CNEGSTInput")
        self.label_26 = QtWidgets.QLabel(self.BotFrame)
        self.label_26.setGeometry(QtCore.QRect(10, 420, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.BotFrame)
        self.label_27.setGeometry(QtCore.QRect(380, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.LRTypeInput = QtWidgets.QComboBox(self.BotFrame)
        self.LRTypeInput.setGeometry(QtCore.QRect(580, 380, 101, 31))
        self.LRTypeInput.setObjectName("LRTypeInput")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.setItemText(2, "")
        self.ToStationInput = QtWidgets.QLineEdit(self.BotFrame)
        self.ToStationInput.setGeometry(QtCore.QRect(523, 15, 161, 31))
        self.ToStationInput.setText("")
        self.ToStationInput.setReadOnly(False)
        self.ToStationInput.setObjectName("ToStationInput")
        self.DateInput = QtWidgets.QDateTimeEdit(self.BotFrame)
        self.DateInput.setGeometry(QtCore.QRect(1192, 15, 151, 31))
        self.DateInput.setObjectName("DateInput")
        self.label_7 = QtWidgets.QLabel(self.BotFrame)
        self.label_7.setGeometry(QtCore.QRect(387, 55, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.BotFrame)
        self.label_9.setGeometry(QtCore.QRect(1062, 53, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.CNRInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNRInput.setGeometry(QtCore.QRect(192, 53, 161, 31))
        self.CNRInput.setText("")
        self.CNRInput.setReadOnly(False)
        self.CNRInput.setObjectName("CNRInput")
        self.VechicleNumInput = QtWidgets.QLineEdit(self.BotFrame)
        self.VechicleNumInput.setGeometry(QtCore.QRect(877, 16, 171, 31))
        self.VechicleNumInput.setObjectName("VechicleNumInput")
        # self.CLRNumber = QtWidgets.QLineEdit(self.BotFrame)
        # self.CLRNumber.setGeometry(QtCore.QRect(1193, 55, 151, 31))
        # self.CLRNumber.setText("")
        # self.CLRNumber.setReadOnly(False)
        # self.CLRNumber.setObjectName("CLRNumber")
        self.CNEInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNEInput.setGeometry(QtCore.QRect(523, 57, 161, 31))
        self.CNEInput.setText("")
        self.CNEInput.setReadOnly(False)
        self.CNEInput.setObjectName("CNEInput")
        self.label_4 = QtWidgets.QLabel(self.BotFrame)
        self.label_4.setGeometry(QtCore.QRect(12, 13, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_21 = QtWidgets.QLabel(self.BotFrame)
        self.label_21.setGeometry(QtCore.QRect(702, 14, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_6 = QtWidgets.QLabel(self.BotFrame)
        self.label_6.setGeometry(QtCore.QRect(385, 13, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.BotFrame)
        self.label_5.setGeometry(QtCore.QRect(12, 53, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.BotFrame)
        self.label_8.setGeometry(QtCore.QRect(1062, 14, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.FrStationInput = QtWidgets.QLineEdit(self.BotFrame)
        self.FrStationInput.setGeometry(QtCore.QRect(192, 13, 161, 31))
        self.FrStationInput.setText("")
        self.FrStationInput.setReadOnly(False)
        self.FrStationInput.setObjectName("FrStationInput")
        self.TopFrame = QtWidgets.QFrame(self.tab)
        self.TopFrame.setGeometry(QtCore.QRect(0, -10, 1351, 431))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.TopFrame.setFont(font)
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.TableAreaTop = QtWidgets.QTableView(self.TopFrame)
        self.TableAreaTop.setGeometry(QtCore.QRect(0, 51, 1351, 371))
        self.TableAreaTop.setObjectName("TableAreaTop")
        self.label = QtWidgets.QLabel(self.TopFrame)
        self.label.setGeometry(QtCore.QRect(10, 12, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CLRSearchInput = QtWidgets.QLineEdit(self.TopFrame)
        self.CLRSearchInput.setGeometry(QtCore.QRect(180, 12, 241, 31))
        self.CLRSearchInput.setText("")
        self.CLRSearchInput.setObjectName("CLRSearchInput")
        self.SearchLRButton = QtWidgets.QPushButton(self.TopFrame)
        self.SearchLRButton.setGeometry(QtCore.QRect(432, 12, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.SearchLRButton.setFont(font)
        self.SearchLRButton.setObjectName("SearchLRButton")
        self.label_2 = QtWidgets.QLabel(self.TopFrame)
        self.label_2.setGeometry(QtCore.QRect(600, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.DateLabel = QtWidgets.QLabel(self.TopFrame)
        self.DateLabel.setGeometry(QtCore.QRect(700, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.DateLabel.setFont(font)
        self.DateLabel.setObjectName("DateLabel")
        self.label_3 = QtWidgets.QLabel(self.TopFrame)
        self.label_3.setGeometry(QtCore.QRect(970, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.BranchComboBox = QtWidgets.QComboBox(self.TopFrame)
        self.BranchComboBox.setGeometry(QtCore.QRect(1170, 10, 101, 31))
        self.BranchComboBox.setObjectName("BranchComboBox")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.MainTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.InvoiceTopFrame = QtWidgets.QFrame(self.tab_2)
        self.InvoiceTopFrame.setGeometry(QtCore.QRect(0, 0, 1861, 521))
        self.InvoiceTopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InvoiceTopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InvoiceTopFrame.setObjectName("InvoiceTopFrame")
        self.label_15 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_15.setGeometry(QtCore.QRect(12, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 100, 211, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 150, 211, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_16 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_16.setGeometry(QtCore.QRect(12, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 50, 211, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_17 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_17.setGeometry(QtCore.QRect(6, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_7.setGeometry(QtCore.QRect(240, 310, 211, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_18 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_18.setGeometry(QtCore.QRect(10, 310, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_8.setGeometry(QtCore.QRect(240, 360, 211, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_19 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_19.setGeometry(QtCore.QRect(10, 360, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_9.setGeometry(QtCore.QRect(710, 50, 211, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_23 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_23.setGeometry(QtCore.QRect(490, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_10.setGeometry(QtCore.QRect(710, 100, 211, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_24 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_24.setGeometry(QtCore.QRect(490, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_11.setGeometry(QtCore.QRect(710, 150, 211, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_28 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_28.setGeometry(QtCore.QRect(490, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_12.setGeometry(QtCore.QRect(710, 200, 211, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_29 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_29.setGeometry(QtCore.QRect(490, 200, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_13.setGeometry(QtCore.QRect(710, 250, 211, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_30 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_30.setGeometry(QtCore.QRect(490, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_14.setGeometry(QtCore.QRect(710, 300, 211, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_31 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_31.setGeometry(QtCore.QRect(490, 300, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_15.setGeometry(QtCore.QRect(1630, 150, 211, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_32 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_32.setGeometry(QtCore.QRect(1450, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_33.setGeometry(QtCore.QRect(1020, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_34.setGeometry(QtCore.QRect(1450, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_35.setGeometry(QtCore.QRect(1020, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_16.setGeometry(QtCore.QRect(1200, 100, 211, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_36 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_36.setGeometry(QtCore.QRect(1020, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_17.setGeometry(QtCore.QRect(1200, 150, 211, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_37 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_37.setGeometry(QtCore.QRect(1450, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_18.setGeometry(QtCore.QRect(1630, 100, 211, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_19.setGeometry(QtCore.QRect(1200, 50, 211, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_20.setGeometry(QtCore.QRect(1630, 50, 211, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.InvoiceTopFrame)
        self.plainTextEdit.setGeometry(QtCore.QRect(1210, 210, 631, 181))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_38 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_38.setGeometry(QtCore.QRect(1020, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_39.setGeometry(QtCore.QRect(1020, 410, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_21.setGeometry(QtCore.QRect(1210, 410, 631, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.comboBox = QtWidgets.QComboBox(self.InvoiceTopFrame)
        self.comboBox.setGeometry(QtCore.QRect(240, 211, 211, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_40 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_40.setGeometry(QtCore.QRect(10, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.InvoiceTopFrame)
        self.label_41.setGeometry(QtCore.QRect(10, 259, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.lineEdit_22.setGeometry(QtCore.QRect(240, 259, 211, 31))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.InvoiceBotFrame = QtWidgets.QFrame(self.tab_2)
        self.InvoiceBotFrame.setGeometry(QtCore.QRect(0, 520, 1861, 421))
        self.InvoiceBotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InvoiceBotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InvoiceBotFrame.setObjectName("InvoiceBotFrame")
        self.MainTabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1881, 26))
        self.menubar.setObjectName("menubar")
        self.menuLR_Booking = QtWidgets.QMenu(self.menubar)
        self.menuLR_Booking.setObjectName("menuLR_Booking")
        self.menuHep = QtWidgets.QMenu(self.menubar)
        self.menuHep.setObjectName("menuHep")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuInvoice = QtWidgets.QMenu(self.menubar)
        self.menuInvoice.setObjectName("menuInvoice")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPrevious_Records = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Records.setObjectName("actionPrevious_Records")
        self.actionFile_search = QtWidgets.QAction(MainWindow)
        self.actionFile_search.setObjectName("actionFile_search")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuHep.addAction(self.actionPrevious_Records)
        self.menuHep.addAction(self.actionFile_search)
        self.menuHep.addAction(self.actionExport)
        self.menufile.addAction(self.actionExit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuLR_Booking.menuAction())
        self.menubar.addAction(self.menuHep.menuAction())
        self.menubar.addAction(self.menuInvoice.menuAction())

        self.retranslateUi(MainWindow)
        self.MainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Billing Application"))
        self.label_10.setText(_translate("MainWindow", "ITEM Name:"))
        self.label_11.setText(_translate("MainWindow", "QTY:"))
        self.label_20.setText(_translate("MainWindow", "RS .P"))
        self.AddItemButton.setText(_translate("MainWindow", "Add Item"))
        self.TotalAmountLabel.setText(_translate("MainWindow", "1000"))
        self.NewLrButton.setText(_translate("MainWindow", "NEW LR"))
        self.EditLrButton.setText(_translate("MainWindow", "EDIT LR"))
        self.CancelLrButton.setText(_translate("MainWindow", "CANCEL LR"))
        self.PrintLrButton.setText(_translate("MainWindow", "PRINT LR"))
        self.label_22.setText(_translate("MainWindow", "RATE:"))
        self.labbb.setText(_translate("MainWindow", "H Charge:"))
        self.llab1.setText(_translate("MainWindow", "Crossing:"))
        self.label_25.setText(_translate("MainWindow", "CNR GST:"))
        self.label_26.setText(_translate("MainWindow", "CNE GST:"))
        self.label_27.setText(_translate("MainWindow", "LR TYPE:"))
        self.LRTypeInput.setItemText(0, _translate("MainWindow", "TO PAY"))
        self.LRTypeInput.setItemText(1, _translate("MainWindow", "PAID"))
        self.label_7.setText(_translate("MainWindow", "CNE:"))
        self.label_9.setText(_translate("MainWindow", "CLR :"))
        self.label_4.setText(_translate("MainWindow", "From Station:"))
        self.label_21.setText(_translate("MainWindow", "VECHICLE NO:"))
        self.label_6.setText(_translate("MainWindow", "To Station :"))
        self.label_5.setText(_translate("MainWindow", "CNR:"))
        self.label_8.setText(_translate("MainWindow", "Date :"))
        self.label.setText(_translate("MainWindow", "CLR Number:"))
        self.SearchLRButton.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Date:"))
        self.DateLabel.setText(_translate("MainWindow", "0/0/0000"))
        self.label_3.setText(_translate("MainWindow", "Branch Code:"))
        self.BranchComboBox.setItemText(0, _translate("MainWindow", "A"))
        self.BranchComboBox.setItemText(1, _translate("MainWindow", "B"))
        self.BranchComboBox.setItemText(2, _translate("MainWindow", "C"))
        self.BranchComboBox.setItemText(3, _translate("MainWindow", "D"))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab), _translate("MainWindow", "BILLING"))
        self.label_15.setText(_translate("MainWindow", "INVOICE DATE:"))
        self.label_16.setText(_translate("MainWindow", "INVOICE TIME:"))
        self.label_17.setText(_translate("MainWindow", " INVOICE NUMBER:"))
        self.label_18.setText(_translate("MainWindow", "DRIVER NAME:"))
        self.label_19.setText(_translate("MainWindow", "DRIVER LICSENCE NO:"))
        self.label_23.setText(_translate("MainWindow", "MAN.INV.NO:"))
        self.label_24.setText(_translate("MainWindow", "LOADING STAFF:"))
        self.label_28.setText(_translate("MainWindow", "INV.STAFF:"))
        self.label_29.setText(_translate("MainWindow", "TIPS:"))
        self.label_30.setText(_translate("MainWindow", "OWNER NAME:"))
        self.label_31.setText(_translate("MainWindow", "TRANSPORT NAME:"))
        self.label_32.setText(_translate("MainWindow", "COMMISSON:"))
        self.label_33.setText(_translate("MainWindow", "LOAN HIRE:"))
        self.label_34.setText(_translate("MainWindow", "COOLEY:"))
        self.label_35.setText(_translate("MainWindow", "ADVANCE:"))
        self.label_36.setText(_translate("MainWindow", "BALANCE AMT:"))
        self.label_37.setText(_translate("MainWindow", "MANUAL:"))
        self.label_38.setText(_translate("MainWindow", "NOTE#1:"))
        self.label_39.setText(_translate("MainWindow", "NOTE#2:"))
        self.label_40.setText(_translate("MainWindow", "INVOICE STATION:"))
        self.label_41.setText(_translate("MainWindow", "VECHICLE NO:"))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab_2), _translate("MainWindow", "INVOICE"))
        self.menuLR_Booking.setTitle(_translate("MainWindow", "LR Booking"))
        self.menuHep.setTitle(_translate("MainWindow", "Search"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuInvoice.setTitle(_translate("MainWindow", "Invoice "))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionPrevious_Records.setText(_translate("MainWindow", "Invoice search"))
        self.actionFile_search.setText(_translate("MainWindow", "File search"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
