# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Billing resizeable.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1888, 1030)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.MainTabWidget.setFont(font)
        self.MainTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.MainTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainTabWidget.setTabsClosable(False)
        self.MainTabWidget.setTabBarAutoHide(False)
        self.MainTabWidget.setObjectName("MainTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopFrame = QtWidgets.QFrame(self.tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.TopFrame.setFont(font)
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TopFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.CLRSearchInput = QtWidgets.QLineEdit(self.TopFrame)
        self.CLRSearchInput.setText("")
        self.CLRSearchInput.setObjectName("CLRSearchInput")
        self.horizontalLayout_3.addWidget(self.CLRSearchInput)
        self.SearchCLRButton = QtWidgets.QPushButton(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.SearchCLRButton.setFont(font)
        self.SearchCLRButton.setObjectName("SearchCLRButton")
        self.horizontalLayout_3.addWidget(self.SearchCLRButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.DateLabel = QtWidgets.QLabel(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.DateLabel.setFont(font)
        self.DateLabel.setObjectName("DateLabel")
        self.horizontalLayout_3.addWidget(self.DateLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.TopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.BranchComboBox = QtWidgets.QComboBox(self.TopFrame)
        self.BranchComboBox.setObjectName("BranchComboBox")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.BranchComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.BranchComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.TableAreaTop = QtWidgets.QFrame(self.TopFrame)
        self.TableAreaTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableAreaTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TableAreaTop.setObjectName("TableAreaTop")
        self.verticalLayout_2.addWidget(self.TableAreaTop)
        self.verticalLayout.addWidget(self.TopFrame)
        self.BotFrame = QtWidgets.QFrame(self.tab)
        self.BotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BotFrame.setObjectName("BotFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.BotFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.CNRInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNRInput.setText("")
        self.CNRInput.setReadOnly(False)
        self.CNRInput.setObjectName("CNRInput")
        self.gridLayout.addWidget(self.CNRInput, 1, 1, 1, 1)
        self.CLRNumber = QtWidgets.QLineEdit(self.BotFrame)
        self.CLRNumber.setText("")
        self.CLRNumber.setReadOnly(False)
        self.CLRNumber.setObjectName("CLRNumber")
        self.gridLayout.addWidget(self.CLRNumber, 1, 10, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 6, 1, 1)
        self.FrStationInput = QtWidgets.QLineEdit(self.BotFrame)
        self.FrStationInput.setText("")
        self.FrStationInput.setReadOnly(False)
        self.FrStationInput.setObjectName("FrStationInput")
        self.gridLayout.addWidget(self.FrStationInput, 0, 1, 1, 1)
        self.DateInput = QtWidgets.QDateTimeEdit(self.BotFrame)
        self.DateInput.setObjectName("DateInput")
        self.gridLayout.addWidget(self.DateInput, 0, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.ToStationInput = QtWidgets.QLineEdit(self.BotFrame)
        self.ToStationInput.setObjectName("ToStationInput")
        self.gridLayout.addWidget(self.ToStationInput, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 5, 1, 1)
        self.CNEInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNEInput.setText("")
        self.CNEInput.setReadOnly(False)
        self.CNEInput.setObjectName("CNEInput")
        self.gridLayout.addWidget(self.CNEInput, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 9, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 9, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 8, 1, 1)
        self.VechicleNumInput = QtWidgets.QLineEdit(self.BotFrame)
        self.VechicleNumInput.setObjectName("VechicleNumInput")
        self.gridLayout.addWidget(self.VechicleNumInput, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.TableAreaBottom = QtWidgets.QFrame(self.BotFrame)
        self.TableAreaBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableAreaBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TableAreaBottom.setObjectName("TableAreaBottom")
        self.verticalLayout_3.addWidget(self.TableAreaBottom)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labbb = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.labbb.setFont(font)
        self.labbb.setObjectName("labbb")
        self.gridLayout_2.addWidget(self.labbb, 5, 6, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PrintLrButton = QtWidgets.QPushButton(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.PrintLrButton.setFont(font)
        self.PrintLrButton.setObjectName("PrintLrButton")
        self.horizontalLayout_4.addWidget(self.PrintLrButton)
        self.CancelLrButton = QtWidgets.QPushButton(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.CancelLrButton.setFont(font)
        self.CancelLrButton.setObjectName("CancelLrButton")
        self.horizontalLayout_4.addWidget(self.CancelLrButton)
        self.EditLrButton = QtWidgets.QPushButton(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.EditLrButton.setFont(font)
        self.EditLrButton.setObjectName("EditLrButton")
        self.horizontalLayout_4.addWidget(self.EditLrButton)
        self.NewLrButton = QtWidgets.QPushButton(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.NewLrButton.setFont(font)
        self.NewLrButton.setObjectName("NewLrButton")
        self.horizontalLayout_4.addWidget(self.NewLrButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.LRTypeInput = QtWidgets.QComboBox(self.BotFrame)
        self.LRTypeInput.setObjectName("LRTypeInput")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.addItem("")
        self.LRTypeInput.setItemText(2, "")
        self.gridLayout_2.addWidget(self.LRTypeInput, 6, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 7, 2, 1, 1)
        self.llab1 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.llab1.setFont(font)
        self.llab1.setObjectName("llab1")
        self.gridLayout_2.addWidget(self.llab1, 6, 6, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 6, 5, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.CNRGSTInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNRGSTInput.setObjectName("CNRGSTInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CNRGSTInput)
        self.label_26 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.CNEGSTInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CNEGSTInput.setObjectName("CNEGSTInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CNEGSTInput)
        self.label_25 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.gridLayout_2.addLayout(self.formLayout, 6, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 10, 1, 1)
        self.HChargeInput = QtWidgets.QLineEdit(self.BotFrame)
        self.HChargeInput.setObjectName("HChargeInput")
        self.gridLayout_2.addWidget(self.HChargeInput, 5, 7, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 7, 10, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 7, 3, 1, 1)
        self.CrossingInput = QtWidgets.QLineEdit(self.BotFrame)
        self.CrossingInput.setObjectName("CrossingInput")
        self.gridLayout_2.addWidget(self.CrossingInput, 6, 7, 1, 1)
        self.TotalAmountLabel = QtWidgets.QLabel(self.BotFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.TotalAmountLabel.setFont(font)
        self.TotalAmountLabel.setObjectName("TotalAmountLabel")
        self.gridLayout_2.addWidget(self.TotalAmountLabel, 5, 9, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 5, 8, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.BotFrame)
        self.MainTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.InvoiceTopFrame = QtWidgets.QFrame(self.tab_2)
        self.InvoiceTopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InvoiceTopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InvoiceTopFrame.setObjectName("InvoiceTopFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.InvoiceTopFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.InvoiceTopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.InvoiceTopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 1, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.InvoiceTopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.PrintInvoiceNumInput = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.PrintInvoiceNumInput.setObjectName("PrintInvoiceNumInput")
        self.gridLayout_3.addWidget(self.PrintInvoiceNumInput, 0, 1, 1, 1)
        self.ChangeAsButtonCalInvoice = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.ChangeAsButtonCalInvoice.setObjectName("ChangeAsButtonCalInvoice")
        self.gridLayout_3.addWidget(self.ChangeAsButtonCalInvoice, 0, 6, 1, 1)
        self.InvoiceVechicleNumInput = QtWidgets.QLineEdit(self.InvoiceTopFrame)
        self.InvoiceVechicleNumInput.setObjectName("InvoiceVechicleNumInput")
        self.gridLayout_3.addWidget(self.InvoiceVechicleNumInput, 1, 6, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.InvoiceTopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 0, 8, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.InvoiceTopFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 1, 0, 1, 1)
        self.InvoiceBranchCode = QtWidgets.QComboBox(self.InvoiceTopFrame)
        self.InvoiceBranchCode.setObjectName("InvoiceBranchCode")
        self.InvoiceBranchCode.addItem("")
        self.InvoiceBranchCode.addItem("")
        self.InvoiceBranchCode.addItem("")
        self.InvoiceBranchCode.addItem("")
        self.gridLayout_3.addWidget(self.InvoiceBranchCode, 0, 10, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.InvoiceTopFrame)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 0, 7, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addWidget(self.InvoiceTopFrame)
        self.InvoiceBotFrame = QtWidgets.QFrame(self.tab_2)
        self.InvoiceBotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InvoiceBotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InvoiceBotFrame.setObjectName("InvoiceBotFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.InvoiceBotFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LRInvoiceSearchInput = QtWidgets.QLineEdit(self.InvoiceBotFrame)
        self.LRInvoiceSearchInput.setText("")
        self.LRInvoiceSearchInput.setObjectName("LRInvoiceSearchInput")
        self.gridLayout_4.addWidget(self.LRInvoiceSearchInput, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 4, 1, 1)
        self.InvoicePrintButton = QtWidgets.QPushButton(self.InvoiceBotFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.InvoicePrintButton.setFont(font)
        self.InvoicePrintButton.setObjectName("InvoicePrintButton")
        self.gridLayout_4.addWidget(self.InvoicePrintButton, 3, 5, 1, 1)
        self.InvoiceMainTableView = QtWidgets.QTableView(self.InvoiceBotFrame)
        self.InvoiceMainTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.InvoiceMainTableView.setObjectName("InvoiceMainTableView")
        self.gridLayout_4.addWidget(self.InvoiceMainTableView, 2, 0, 1, 6)
        self.label_12 = QtWidgets.QLabel(self.InvoiceBotFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 0, 3, 1, 1)
        self.LRSearchInvoiceButton = QtWidgets.QPushButton(self.InvoiceBotFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.LRSearchInvoiceButton.setFont(font)
        self.LRSearchInvoiceButton.setObjectName("LRSearchInvoiceButton")
        self.gridLayout_4.addWidget(self.LRSearchInvoiceButton, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addWidget(self.InvoiceBotFrame)
        self.MainTabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.MainTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1888, 26))
        self.menubar.setObjectName("menubar")
        self.menuHep = QtWidgets.QMenu(self.menubar)
        self.menuHep.setObjectName("menuHep")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuPrinter_config = QtWidgets.QMenu(self.menubar)
        self.menuPrinter_config.setObjectName("menuPrinter_config")
        self.menuShortcuts = QtWidgets.QMenu(self.menubar)
        self.menuShortcuts.setObjectName("menuShortcuts")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPrevious_Records = QtWidgets.QAction(MainWindow)
        self.actionPrevious_Records.setObjectName("actionPrevious_Records")
        self.actionFile_search = QtWidgets.QAction(MainWindow)
        self.actionFile_search.setObjectName("actionFile_search")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionChange_password = QtWidgets.QAction(MainWindow)
        self.actionChange_password.setObjectName("actionChange_password")
        self.actionCreate_User = QtWidgets.QAction(MainWindow)
        self.actionCreate_User.setObjectName("actionCreate_User")
        self.menuHep.addAction(self.actionPrevious_Records)
        self.menuHep.addAction(self.actionFile_search)
        self.menuHep.addAction(self.actionExport)
        self.menufile.addAction(self.actionCreate_User)
        self.menufile.addAction(self.actionChange_password)
        self.menufile.addAction(self.actionExit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuHep.menuAction())
        self.menubar.addAction(self.menuPrinter_config.menuAction())
        self.menubar.addAction(self.menuShortcuts.menuAction())

        self.retranslateUi(MainWindow)
        self.MainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.FrStationInput, self.ToStationInput)
        MainWindow.setTabOrder(self.ToStationInput, self.CNRInput)
        MainWindow.setTabOrder(self.CNRInput, self.CNEInput)
        MainWindow.setTabOrder(self.CNEInput, self.NewLrButton)
        MainWindow.setTabOrder(self.NewLrButton, self.CNRGSTInput)
        MainWindow.setTabOrder(self.CNRGSTInput, self.CNEGSTInput)
        MainWindow.setTabOrder(self.CNEGSTInput, self.BranchComboBox)
        MainWindow.setTabOrder(self.BranchComboBox, self.MainTabWidget)
        MainWindow.setTabOrder(self.MainTabWidget, self.DateInput)
        MainWindow.setTabOrder(self.DateInput, self.PrintLrButton)
        MainWindow.setTabOrder(self.PrintLrButton, self.CancelLrButton)
        MainWindow.setTabOrder(self.CancelLrButton, self.EditLrButton)
        MainWindow.setTabOrder(self.EditLrButton, self.CLRNumber)
        MainWindow.setTabOrder(self.CLRNumber, self.VechicleNumInput)
        MainWindow.setTabOrder(self.VechicleNumInput, self.CLRSearchInput)
        MainWindow.setTabOrder(self.CLRSearchInput, self.SearchCLRButton)
        MainWindow.setTabOrder(self.SearchCLRButton, self.PrintInvoiceNumInput)
        MainWindow.setTabOrder(self.PrintInvoiceNumInput, self.ChangeAsButtonCalInvoice)
        MainWindow.setTabOrder(self.ChangeAsButtonCalInvoice, self.InvoiceVechicleNumInput)
        MainWindow.setTabOrder(self.InvoiceVechicleNumInput, self.InvoiceBranchCode)
        MainWindow.setTabOrder(self.InvoiceBranchCode, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.LRInvoiceSearchInput)
        MainWindow.setTabOrder(self.LRInvoiceSearchInput, self.InvoicePrintButton)
        MainWindow.setTabOrder(self.InvoicePrintButton, self.InvoiceMainTableView)
        MainWindow.setTabOrder(self.InvoiceMainTableView, self.LRSearchInvoiceButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Billing Application"))
        self.label.setText(_translate("MainWindow", "CLR Number:"))
        self.SearchCLRButton.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Date:"))
        self.DateLabel.setText(_translate("MainWindow", "0/0/0000"))
        self.label_3.setText(_translate("MainWindow", "Branch Code:"))
        self.BranchComboBox.setItemText(0, _translate("MainWindow", "A"))
        self.BranchComboBox.setItemText(1, _translate("MainWindow", "B"))
        self.BranchComboBox.setItemText(2, _translate("MainWindow", "C"))
        self.BranchComboBox.setItemText(3, _translate("MainWindow", "D"))
        self.label_7.setText(_translate("MainWindow", "CNE:"))
        self.label_4.setText(_translate("MainWindow", "From Station:"))
        self.label_21.setText(_translate("MainWindow", "VECHICLE NO:"))
        self.label_6.setText(_translate("MainWindow", "To Station :"))
        self.label_9.setText(_translate("MainWindow", "CLR :"))
        self.label_8.setText(_translate("MainWindow", "Date :"))
        self.label_5.setText(_translate("MainWindow", "CNR:"))
        self.labbb.setText(_translate("MainWindow", "H Charge:"))
        self.PrintLrButton.setText(_translate("MainWindow", "PRINT LR"))
        self.CancelLrButton.setText(_translate("MainWindow", "CANCEL LR"))
        self.EditLrButton.setText(_translate("MainWindow", "EDIT LR"))
        self.NewLrButton.setText(_translate("MainWindow", "NEW LR"))
        self.LRTypeInput.setItemText(0, _translate("MainWindow", "TO PAY"))
        self.LRTypeInput.setItemText(1, _translate("MainWindow", "PAID"))
        self.llab1.setText(_translate("MainWindow", "Crossing:"))
        self.label_27.setText(_translate("MainWindow", "LR TYPE:"))
        self.label_26.setText(_translate("MainWindow", "CNE GST:"))
        self.label_25.setText(_translate("MainWindow", "CNR GST:"))
        self.label_20.setText(_translate("MainWindow", "RS .P"))
        self.TotalAmountLabel.setText(_translate("MainWindow", "1000"))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab), _translate("MainWindow", "BILLING"))
        self.label_15.setText(_translate("MainWindow", "INVOICE DATE:"))
        self.label_41.setText(_translate("MainWindow", "VECHICLE NO:"))
        self.label_17.setText(_translate("MainWindow", "PR.INVOICE NUMBER:"))
        self.label_45.setText(_translate("MainWindow", "Branch Code:"))
        self.label_40.setText(_translate("MainWindow", "INVOICE STATION:"))
        self.InvoiceBranchCode.setItemText(0, _translate("MainWindow", "A"))
        self.InvoiceBranchCode.setItemText(1, _translate("MainWindow", "B"))
        self.InvoiceBranchCode.setItemText(2, _translate("MainWindow", "C"))
        self.InvoiceBranchCode.setItemText(3, _translate("MainWindow", "D"))
        self.InvoicePrintButton.setText(_translate("MainWindow", "PRINT LR"))
        self.label_12.setText(_translate("MainWindow", "LR Number:"))
        self.LRSearchInvoiceButton.setText(_translate("MainWindow", "Search"))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab_2), _translate("MainWindow", "INVOICE"))
        self.menuHep.setTitle(_translate("MainWindow", "Search"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuPrinter_config.setTitle(_translate("MainWindow", "Printer config"))
        self.menuShortcuts.setTitle(_translate("MainWindow", "Shortcuts"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionPrevious_Records.setText(_translate("MainWindow", "Invoice search"))
        self.actionFile_search.setText(_translate("MainWindow", "File search"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionChange_password.setText(_translate("MainWindow", "Change password"))
        self.actionCreate_User.setText(_translate("MainWindow", "Create User"))
